name: OrbitHCF
version: 1.0-SNAPSHOT
main: me.christo.orbithcf.Main
api-version: 1.13
authors: [Christo]
description: Switcher Balls, and Bard.
website: http://www.devchristo.com/
commands:
  bard:
    description: Gives the bard item.
  switcher:
    description: Gives the switcher ball.
